spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate #usamos o create para ele criar as tabelas Entity e depois voltamos com validate só para validar as tabelas existente e não cria-las novamente.
